require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - '*.gemspec'
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - bin/mutant
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-latex-block.rb'
