AllCops:
  Include:
    - '*.gemspec'
    - '**/*.rb'
    - Gemfile
    - Rakefile
  Exclude:
    - bin/rake
    - bin/rubocop
    - 'vendor/**/*'

Naming/FileName:
  Exclude:
    - 'lib/jekyll-latex-block.rb'
